# Generated by Django 6.0.2 on 2026-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.IntegerField(help_text='Days remaining')),
                ('estimated_time', models.FloatField(help_text='Hours required')),
                ('importance', models.IntegerField(help_text='1-10 scale')),
                ('priority_score', models.FloatField(default=0.0)),
                ('category', models.CharField(default='Pending', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
